name = "EXR"
uuid = "d7f3f428-7e66-4c45-affc-2af92c4fb122"
version = "0.1.0"
authors = ["CÃ©dric BELMANT"]

[deps]
BinaryParsingTools = "6663bfc4-f836-4634-93ec-aee42a53a86a"
BitMasks = "a3e06817-fd65-4797-8291-16f435bc2529"

[compat]
BitMasks = "0.1.6"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
